# Generated by Django 2.2.8 on 2019-12-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191220_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='Default Content', upload_to='blog/images/'),
            preserve_default=False,
        ),
    ]
