# Generated by Django 2.2.8 on 2019-12-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191222_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
    ]
